### ISSUE TITLE
How do you generate the PDF from the MD files?

### ISSUE THREAD

**Issue by Wolfcast** [archivistsguidetokryoflux/archivists-guide-to-kryoflux#4]
Can you please add how to create the PDF from the MD files so we can regenerate an up to date file from the MD files in the repo?

Thanks!

**Comment by laissezfarrell** [comment]
Hello - 
A PDF copy is in this repository: https://github.com/archivistsguidetokryoflux/archivists-guide-to-kryoflux/blob/master/Archivist's%20Guide%20to%20KryoFlux_20180801.pdf

**Comment by Wolfcast** [comment]
I know but it's not up to date. I wanted to know how to regenerate it with up to date information?

**Comment by laissezfarrell** [comment]
There are solutions beyond the scope of this project to generate PDF from markdown files. Some text editors (e.g., Atom) have plugins to do so, and I believe pandoc (https://pandoc.org/) is worth exploring. 

Thanks for pointing out that the PDF linked above is outdated. I'll try to address it as I can, but not sure on what timeline.

**Comment by Wolfcast** [comment]
Thanks! I already tried several app on different platform to reproduce the PDF in the repo without success (thus asking for your recipe) as it's easy to do for a simple single MD to PDF, but haven't found a converter that mash all the MD of a repo in a single PDF with formatting and images. I will wait for the newer PDF on the repo. Thanks for your work!
